language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: none
      dotnet: 1.1.0
    - os: osx
      osx_image: xcode8
      dotnet: 1.1.0

branches:
  only:
  - master

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.0.1

before_script:
  - chmod a+x ./scripts/travis-build.sh
  - chmod a+x ./scripts/travis-test.sh

script:
  - ./scripts/travis-build.sh
  - ./scripts/travis-test.sh